### PR TITLE
Add tests for various file types uploads

### PR DESCRIPTION
**Pull request by AlexandraMoga**
This PR includes:
- tests for supported file type uploads
- tests for unsupported and corrupt/invalid file types
- tests for theme submissions

### CODE REVIEW

**Comment by jrbenny35** [comment]
Do these files contain anything?

**Comment by AlexandraMoga** [comment]
> Do these files contain anything?

@jrbenny35 they are  simplified addon files, mostly containing a `manifest.json` with valid addon properties. If they'd been `.zip` files, they would pass validation, but as unsupported archive formats they will fail at upload time.

**Comment by AlexandraMoga** [comment]
> Why don't you try making the files dynamically? That would save some space, especially if all the files are the same

I've looked into the possibilities a bit. It looks like python has a built in `tarfile` module that could create the `tgz` and `tar.gz` files. For `7z` I will need another library (https://py7zr.readthedocs.io/en/latest/user_guide.html) which adds to our requirements. 
I haven't found a module that can create `crx` archives through python, only some unpacking tool (https://pypi.org/project/crx-unpack/) which doesn't help.

As for the broken archives, those need to be broken in a specific way, so it's not something that can be done easily through a script. 

This leaves me with two,  potentially three (if I install the `py7zr` requirement) archives that can be created dynamically, which will save us a 3 KB at most in total. I'm not sure if this is worth it.

**Comment by jrbenny35** [comment]
> As for the broken archives, those need to be broken in a specific way, so it's not something that can be done easily through a script.

What specific way?

I found an example of what I mean in the amo repo [https://github.com/mozilla/addons-server/blob/3109cfb8c40d3db22df9737bedf38c44091cf237/src/olympia/devhub/tests/test_views_versions.py#L932](here). For the ```.crx``` file, it would be as simple as changing a ```.zip``` to a ```.crx```, so you could make that file as a zip and change it. You're correct about ```tarfile``` and that would take care of the other 2. ```.7z``` is a bit trickier though, as you found.

So with that link I posted, do we need to do these tests? They also seem to have a directory where they test a lot of file types, [https://github.com/mozilla/addons-server/tree/2c98d69731bd4f12b5a85df8ee443e95e8a7bdef/src/olympia/files/fixtures/files](here), I almost think adding a ```.7z``` file there and having them add it to their tests is a better idea.

**Comment by jrbenny35** [comment]
Thanks for those comments. I think you're not far off but I feel you're missing a part to make it truly end-to-end. Right now, as I look at these tests, I see very similar tests inside of the addons-server repo, just done through the UI. I don't think that is quite what we want here for end-to-end. The tests within addons-server are very unit style, as they're just stressing the APIs/etc. 

Do you have any thoughts on how we can extend this testing to make it more of what a user would do but not so close to just what the unit tests do now?

**Comment by AlexandraMoga** [comment]
So my idea for an end-to-end test tackling unsupported file types would be the following:
- as a user, identify the API endpoints which allow addon submissions on AMO -namely, [upload](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#upload-create) and [create](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#create) addon 
- choose an unsupported file type to upload - i.e. `.7z`
- create the upload and submit the addon 
- check the API response => it should be 400 - (I've just noticed that I forgot to add the create step in my tests and I was directly inspecting the validation errors without trying to create the addon and see the 400 first; I will add this step)
- try to find out what went wrong with your upload  by interrogating the [upload detail](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#upload-detail) endpoint 
- identify the validation error messages, which should point to the unsupported file type uploaded, i.e. `'Unsupported file type, please upload a supported file (.crx, .xpi, .zip).'`


Although the tests looks similar to what the devs have in their unit tests, my tests are specifically using the API endpoints a user will try to access to identify the problem with their upload. 

As another example, if the devs asked QA to do a regression on unsupported addon types submissions through the API, this is a template we would follow.

**Comment by jrbenny35** [comment]
Thanks for that explanation. In the end, these are your tests so whatever you see as valuable, then I'm all for that.

**Review by jrbenny35 — APPROVED** [review]

**Pull request merged**
